# Populated with sample values to allow both the ESP32 device and a local MQTT listener to connect

per_listener_settings true

listener 8883
accept_protocol_versions 3, 4

cafile certs/broker.crt
certfile certs/broker.crt
keyfile certs/broker.key
require_certificate true
use_identity_as_username true

listener 1883 127.0.0.1
accept_protocol_versions 3, 4
allow_anonymous true
